apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sh-async-api.fullname" . }}-myapp-ingress
  labels:
  {{- include "sh-async-api.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: myapp-service
            port:
              number: 8443
        path: /testpath
        pathType: Prefix