apiVersion: v1
kind: Service
metadata:
  name: {{ include "sh-async-api.fullname" . }}-nginx
  labels:
    app: nginx
  {{- include "sh-async-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.type }}
  selector:
    app: nginx
  {{- include "sh-async-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nginx.ports | toYaml | nindent 2 -}}