apiVersion: v1
kind: Service
metadata:
  name: {{ include "sh-async-api.fullname" . }}-sh-async-api
  labels:
    app: sh-async-api
  {{- include "sh-async-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.shAsyncApi.type }}
  selector:
    app: sh-async-api
  {{- include "sh-async-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.shAsyncApi.ports | toYaml | nindent 2 -}}